kind: Deployment
apiVersion: apps/v1
metadata:
  name: node-deployment
  namespace: node
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-pod
        image: swayamnakshane/demoapp:latest
        ports:
        - containerPort: 3000                 s
